### ISSUE TITLE
It does not work in 1.13

### ISSUE THREAD

**Issue by dhgameryt** [Skyost/OwnGarden#6]
I get this error when growing a tree, and the schematic does not come out, I'm in 1.13

[19:24:45 ERROR]: Could not pass event StructureGrowEvent to OwnGarden v0.2 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.ItemStack.placeItem(ItemStack.java:176) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:500) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172] at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172] Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.extent.clipboard.Clipboard.getDimensions()Lcom/sk89q/worldedit/Vector; at fr.skyost.owngarden.listener.GlobalEvents.growBlock(GlobalEvents.java:126) ~[?:?] at fr.skyost.owngarden.listener.GlobalEvents.onStructureGrow(GlobalEvents.java:61) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

**Comment by Skyost** [comment]
What version of WorldEdit is installed on your server ?

**Comment by dhgameryt** [comment]
worldedit-bukkit-7.0.0-SNAPSHOT-dist

is latest release version

**Comment by Skyost** [comment]
Don't use a snapshot. [Here](https://dev.bukkit.org/projects/worldedit/files/2618989/download) is the latest version.

**Comment by dhgameryt** [comment]
Thank you very much, it works well for me, I'll keep in mind, do not use snapshots, I'm glad you answered me.
Very good plugin that you have done, original and without bugs.
