### ISSUE TITLE
Could not pass event StructureGrowEvent to OwnGarden v0.2 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by Angelt9Dev** [Skyost/OwnGarden#9]
[12:41:15 ERROR]: Could not pass event StructureGrowEvent to OwnGarden v0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.BlockSapling.a(BlockSapling.java:49) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.Block.b(Block.java:364) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.IBlockData.b(SourceFile:265) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:555) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:305) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:956) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.extent.clipboard.Clipboard.getDimensions()Lcom/sk89q/worldedit/Vector;
        at fr.skyost.owngarden.listener.GlobalEvents.growBlock(GlobalEvents.java:126) ~[?:?]
        at fr.skyost.owngarden.listener.GlobalEvents.onStructureGrow(GlobalEvents.java:64) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-latest.jar:git-Spigot-a1ba5fe-3359cb1]
        ... 13 more

Can you help me ? Thanks
Discord : Angelt9Dev#0001

**Comment by Skyost** [comment]
Going to be fixed in the next update.
